-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone_number character varying NOT NULL UNIQUE,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  profile_picture_url character varying,
  role character varying NOT NULL DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['user'::character varying, 'driver'::character varying, 'admin'::character varying, 'super_admin'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['active'::text, 'suspended'::text, 'pending'::text, 'deleted'::text])),
  profile_complete boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  emergency_contact character varying,
  emergency_phone character varying,
  password_reset_token character varying,
  password_reset_expiry timestamp without time zone,
  deleted_at timestamp without time zone,
  deletion_reason text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.drivers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  vehicle_type character varying,
  plate_number character varying UNIQUE,
  operating_zones ARRAY DEFAULT ARRAY[]::text[],
  availability_status character varying DEFAULT 'offline'::character varying CHECK (availability_status::text = ANY (ARRAY['online'::character varying, 'offline'::character varying, 'busy'::character varying]::text[])),
  bank_name character varying,
  bank_account_number character varying,
  emergency_contact character varying,
  verified boolean DEFAULT false,
  vehicle_picture_url character varying,
  license_picture_url character varying,
  total_rides_completed integer DEFAULT 0,
  average_rating numeric DEFAULT 0.00,
  total_earnings numeric DEFAULT 0.00,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  account_name character varying,
  guarantor_name text,
  guarantor_phone text,
  guarantor_address text,
  bank_code text,
  nin_number text,
  identity_type text NOT NULL DEFAULT 'nin'::text CHECK (identity_type = 'nin'::text),
  identity_last4 text,
  identity_document_url text,
  identity_verified boolean NOT NULL DEFAULT false,
  identity_verification_status text NOT NULL DEFAULT 'not_started'::text CHECK (identity_verification_status = ANY (ARRAY['not_started'::text, 'pending_details'::text, 'pending'::text, 'verified'::text, 'failed'::text])),
  identity_verification_provider text,
  identity_verification_reference text,
  identity_verification_reason text,
  identity_verification_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  identity_verified_at timestamp with time zone,
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  admin_level character varying NOT NULL DEFAULT 'support'::character varying CHECK (admin_level::text = ANY (ARRAY['support'::character varying, 'ops'::character varying, 'finance'::character varying, 'super'::character varying]::text[])),
  permissions jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  department character varying NOT NULL DEFAULT 'general'::character varying,
  crm_enabled boolean NOT NULL DEFAULT true,
  crm_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT admins_pkey PRIMARY KEY (id),
  CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT 0,
  currency character varying DEFAULT 'NGN'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  ride_id uuid,
  amount numeric NOT NULL,
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['credit'::character varying, 'debit'::character varying, 'payout'::character varying, 'refund'::character varying]::text[])),
  reference character varying,
  source character varying NOT NULL CHECK (source::text = ANY (ARRAY['ride'::character varying, 'admin_adjustment'::character varying, 'payout'::character varying, 'deposit'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  description text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(id)
);
CREATE TABLE public.rides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rider_id uuid NOT NULL,
  driver_id uuid,
  pickup_zone character varying NOT NULL,
  pickup_description text,
  destination_zone character varying NOT NULL,
  destination_description text,
  ride_type character varying NOT NULL DEFAULT 'shared'::character varying CHECK (ride_type::text = ANY (ARRAY['single'::character varying, 'shared'::character varying, 'delivery'::character varying]::text[])),
  fare_amount numeric,
  driver_earnings numeric,
  platform_fee numeric,
  seats_available integer DEFAULT 1,
  seats_booked integer DEFAULT 1,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'dispatched'::character varying, 'accepted'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  cancellation_reason character varying,
  pickup_time timestamp without time zone,
  dropoff_time timestamp without time zone,
  duration_minutes integer,
  distance_km numeric,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  review text,
  created_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  updated_at timestamp without time zone DEFAULT now(),
  remitted boolean NOT NULL DEFAULT false,
  remitted_at timestamp without time zone,
  remitted_by_payment_id uuid,
  eta_minutes integer,
  CONSTRAINT rides_pkey PRIMARY KEY (id),
  CONSTRAINT rides_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.users(id),
  CONSTRAINT rides_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT rides_remitted_by_payment_fkey FOREIGN KEY (remitted_by_payment_id) REFERENCES public.driver_payments(id)
);
CREATE TABLE public.ride_dispatch_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ride_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  dispatch_method character varying NOT NULL CHECK (dispatch_method::text = ANY (ARRAY['sms'::character varying, 'push'::character varying, 'app'::character varying]::text[])),
  response character varying CHECK (response::text = ANY (ARRAY['accepted'::character varying, 'rejected'::character varying, 'timeout'::character varying]::text[])),
  response_time integer,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT ride_dispatch_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ride_dispatch_logs_ride_id_fkey FOREIGN KEY (ride_id) REFERENCES public.rides(id),
  CONSTRAINT ride_dispatch_logs_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referee_id uuid,
  referral_code character varying NOT NULL UNIQUE,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'claimed'::character varying]::text[])),
  reward_amount numeric,
  created_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.users(id),
  CONSTRAINT referrals_referee_id_fkey FOREIGN KEY (referee_id) REFERENCES public.users(id)
);
CREATE TABLE public.ride_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ride_id uuid NOT NULL UNIQUE,
  reviewer_id uuid NOT NULL,
  rated_user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text,
  categories jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT ride_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT ride_reviews_ride_id_fkey FOREIGN KEY (ride_id) REFERENCES public.rides(id),
  CONSTRAINT ride_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT ride_reviews_rated_user_id_fkey FOREIGN KEY (rated_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying NOT NULL DEFAULT 'system'::character varying CHECK (type IS NOT NULL AND length(TRIM(BOTH FROM type::text)) >= 1 AND length(TRIM(BOTH FROM type::text)) <= 80 AND type::text !~ '[[:space:]]'::text),
  channel character varying NOT NULL DEFAULT 'in_app'::character varying CHECK (channel::text = ANY (ARRAY['in_app'::character varying, 'push'::character varying, 'sms'::character varying, 'email'::character varying]::text[])),
  related_table character varying,
  related_id uuid,
  read boolean DEFAULT false,
  read_at timestamp without time zone,
  action_url character varying,
  data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  deep_link text,
  entity_type text,
  entity_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  deeplink text,
  target_type character varying,
  target_id uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  push_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT true,
  email_enabled boolean DEFAULT true,
  ride_notifications boolean DEFAULT true,
  payment_notifications boolean DEFAULT true,
  admin_notifications boolean DEFAULT true,
  marketing_notifications boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  priority character varying NOT NULL DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  assigned_to uuid,
  related_ride_id uuid,
  created_at timestamp without time zone DEFAULT now(),
  resolved_at timestamp without time zone,
  updated_at timestamp without time zone DEFAULT now(),
  resolution_note text,
  resolution_requested_at timestamp without time zone,
  resolution_confirmed_at timestamp without time zone,
  user_last_read_at timestamp without time zone,
  admin_last_read_at timestamp without time zone,
  last_message_at timestamp without time zone DEFAULT now(),
  closed_by_user boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  department_id uuid,
  source_channel character varying NOT NULL DEFAULT 'in_app'::character varying,
  source_email character varying,
  source_name character varying,
  external_thread_id character varying,
  external_message_id character varying,
  routing_reason text,
  routing_confidence numeric NOT NULL DEFAULT 0,
  crm_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  conversation_id uuid,
  case_number integer,
  case_source character varying NOT NULL DEFAULT 'manual'::character varying CHECK (case_source::text = ANY (ARRAY['manual'::character varying, 'ai'::character varying, 'email'::character varying, 'admin'::character varying]::text[])),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.admins(id),
  CONSTRAINT support_tickets_related_ride_id_fkey FOREIGN KEY (related_ride_id) REFERENCES public.rides(id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT support_tickets_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.crm_departments(id),
  CONSTRAINT support_tickets_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.support_conversations(id)
);
CREATE TABLE public.ticket_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  message text NOT NULL,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'image'::character varying, 'system'::character varying]::text[])),
  attachment_url text,
  attachment_name character varying,
  attachment_mime_type character varying,
  attachment_size bigint,
  is_internal boolean DEFAULT false,
  updated_at timestamp without time zone DEFAULT now(),
  sender_type character varying NOT NULL DEFAULT 'user'::character varying CHECK (sender_type::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'support'::character varying, 'admin'::character varying, 'system'::character varying]::text[])),
  sender_label text,
  department_key character varying,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT ticket_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  changes jsonb,
  ip_address character varying,
  user_agent character varying,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.system_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  metric_name character varying NOT NULL,
  metric_value numeric,
  metric_date date NOT NULL,
  metric_hour integer,
  tags jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT system_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  referral_code character varying NOT NULL UNIQUE,
  code_type character varying NOT NULL DEFAULT 'personal'::character varying CHECK (code_type::text = ANY (ARRAY['personal'::character varying::text, 'driver'::character varying::text, 'admin'::character varying::text])),
  total_referrals integer NOT NULL DEFAULT 0,
  active_referrals integer NOT NULL DEFAULT 0,
  total_rewards numeric NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT referral_codes_pkey PRIMARY KEY (id),
  CONSTRAINT referral_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.driver_daily_settlement (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  settlement_date date NOT NULL,
  total_rides integer NOT NULL DEFAULT 0,
  total_fare_amount numeric NOT NULL DEFAULT 0,
  total_platform_fees numeric NOT NULL DEFAULT 0,
  total_driver_earnings numeric NOT NULL DEFAULT 0,
  settlement_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (settlement_status::text = ANY (ARRAY['pending'::character varying::text, 'paid'::character varying::text, 'overdue'::character varying::text])),
  payment_due_date timestamp without time zone NOT NULL,
  paid_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  log_id uuid,
  CONSTRAINT driver_daily_settlement_pkey PRIMARY KEY (id),
  CONSTRAINT driver_daily_settlement_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT driver_daily_settlement_log_id_fkey FOREIGN KEY (log_id) REFERENCES public.driver_daily_rides_log(id)
);
CREATE TABLE public.driver_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  settlement_id uuid,
  amount numeric NOT NULL,
  payment_method character varying NOT NULL CHECK (payment_method::text = ANY (ARRAY['paystack'::character varying::text, 'bank_transfer'::character varying::text, 'cash'::character varying::text])),
  payment_reference character varying NOT NULL UNIQUE,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'refunded'::character varying::text])),
  payment_date timestamp without time zone NOT NULL,
  confirmed_at timestamp without time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT driver_payments_pkey PRIMARY KEY (id),
  CONSTRAINT driver_payments_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES public.driver_daily_settlement(id),
  CONSTRAINT driver_payments_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.driver_payment_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  settlement_id uuid NOT NULL,
  reminder_type character varying NOT NULL CHECK (reminder_type::text = ANY (ARRAY['first_notice'::character varying::text, 'second_notice'::character varying::text, 'final_notice'::character varying::text])),
  amount_owed numeric NOT NULL,
  sent_at timestamp without time zone NOT NULL,
  acknowledged_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT driver_payment_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT driver_payment_reminders_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT driver_payment_reminders_settlement_id_fkey FOREIGN KEY (settlement_id) REFERENCES public.driver_daily_settlement(id)
);
CREATE TABLE public.driver_locations (
  id uuid NOT NULL,
  driver_id uuid,
  latitude numeric,
  longitude numeric,
  timestamp timestamp without time zone DEFAULT now(),
  ride_id uuid,
  accuracy numeric,
  speed numeric,
  heading numeric,
  CONSTRAINT driver_locations_pkey PRIMARY KEY (id),
  CONSTRAINT driver_locations_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT driver_locations_ride_id_fkey FOREIGN KEY (ride_id) REFERENCES public.rides(id)
);
CREATE TABLE public.user_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  timestamp timestamp without time zone DEFAULT now(),
  ride_id uuid,
  accuracy numeric,
  speed numeric,
  heading numeric,
  CONSTRAINT user_locations_pkey PRIMARY KEY (id),
  CONSTRAINT user_locations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_locations_ride_id_fkey FOREIGN KEY (ride_id) REFERENCES public.rides(id)
);
CREATE TABLE public.driver_daily_rides_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL,
  log_date date NOT NULL,
  ride_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::text, 'paid'::text, 'overdue'::text])),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT driver_daily_rides_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  push_token text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])),
  subscribed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  last_verified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  phone_number character varying,
  email character varying,
  code character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['resume_session'::character varying, 'forgot_password'::character varying, 'verify_account'::character varying]::text[])),
  is_verified boolean DEFAULT false,
  attempts integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  expires_at timestamp without time zone NOT NULL,
  verified_at timestamp without time zone,
  CONSTRAINT otps_pkey PRIMARY KEY (id),
  CONSTRAINT otps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.chats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ride_id uuid NOT NULL UNIQUE,
  rider_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT chats_pkey PRIMARY KEY (id),
  CONSTRAINT chats_ride_id_fkey FOREIGN KEY (ride_id) REFERENCES public.rides(id),
  CONSTRAINT chats_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.users(id),
  CONSTRAINT chats_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chat_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text,
  message_type character varying NOT NULL DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying::text, 'location'::character varying::text])),
  location_data jsonb,
  sent_at timestamp without time zone DEFAULT now(),
  read_by_rider boolean NOT NULL DEFAULT false,
  read_by_driver boolean NOT NULL DEFAULT false,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.crm_departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  department_key character varying NOT NULL UNIQUE,
  department_name character varying NOT NULL,
  description text,
  email_alias character varying,
  route_priority integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_internal_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL,
  author_admin_id uuid NOT NULL,
  department_id uuid,
  note text NOT NULL,
  visibility character varying NOT NULL DEFAULT 'internal'::character varying CHECK (visibility::text = ANY (ARRAY['internal'::character varying, 'department'::character varying, 'super_admin'::character varying]::text[])),
  mentions jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_internal_notes_pkey PRIMARY KEY (id),
  CONSTRAINT crm_internal_notes_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT crm_internal_notes_author_admin_id_fkey FOREIGN KEY (author_admin_id) REFERENCES public.admins(id),
  CONSTRAINT crm_internal_notes_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.crm_departments(id)
);
CREATE TABLE public.crm_email_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  display_name character varying NOT NULL,
  email_address character varying NOT NULL UNIQUE,
  provider character varying NOT NULL DEFAULT 'custom_imap'::character varying,
  department_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  last_synced_at timestamp without time zone,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_email_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT crm_email_accounts_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.crm_departments(id)
);
CREATE TABLE public.crm_email_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_account_id uuid,
  ticket_id uuid,
  direction character varying NOT NULL CHECK (direction::text = ANY (ARRAY['inbound'::character varying, 'outbound'::character varying]::text[])),
  from_email character varying NOT NULL,
  from_name character varying,
  to_emails jsonb NOT NULL DEFAULT '[]'::jsonb,
  cc_emails jsonb NOT NULL DEFAULT '[]'::jsonb,
  bcc_emails jsonb NOT NULL DEFAULT '[]'::jsonb,
  subject character varying NOT NULL,
  body_text text,
  body_html text,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  external_message_id character varying,
  external_thread_id character varying,
  processing_status character varying NOT NULL DEFAULT 'queued'::character varying CHECK (processing_status::text = ANY (ARRAY['queued'::character varying, 'processed'::character varying, 'failed'::character varying, 'ignored'::character varying]::text[])),
  processing_reason text,
  raw_headers jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  received_at timestamp without time zone NOT NULL DEFAULT now(),
  processed_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_email_messages_pkey PRIMARY KEY (id),
  CONSTRAINT crm_email_messages_email_account_id_fkey FOREIGN KEY (email_account_id) REFERENCES public.crm_email_accounts(id),
  CONSTRAINT crm_email_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id)
);
CREATE TABLE public.crm_routing_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rule_name character varying NOT NULL,
  match_scope character varying NOT NULL DEFAULT 'subject_body'::character varying CHECK (match_scope::text = ANY (ARRAY['subject_body'::character varying, 'recipient'::character varying, 'sender'::character varying, 'all'::character varying]::text[])),
  match_pattern text NOT NULL,
  department_id uuid NOT NULL,
  priority integer NOT NULL DEFAULT 100,
  auto_assign boolean NOT NULL DEFAULT true,
  auto_reply boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_routing_rules_pkey PRIMARY KEY (id),
  CONSTRAINT crm_routing_rules_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.crm_departments(id)
);
CREATE TABLE public.search_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  place_id text NOT NULL UNIQUE,
  name text NOT NULL,
  formatted_address text NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  search_keywords text NOT NULL DEFAULT ''::text,
  usage_count integer NOT NULL DEFAULT 0,
  last_used_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT search_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_user_id uuid NOT NULL,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT admin_push_subscriptions_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.admin_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_user_id uuid,
  recipient_department character varying,
  title text NOT NULL,
  body text NOT NULL,
  type character varying NOT NULL DEFAULT 'admin_event'::character varying,
  action_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT admin_notifications_recipient_user_id_fkey FOREIGN KEY (recipient_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.admin_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_type character varying NOT NULL CHECK (conversation_type::text = ANY (ARRAY['department'::character varying, 'direct'::character varying, 'ticket'::character varying]::text[])),
  department_key character varying,
  ticket_id uuid,
  title text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT admin_conversations_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT admin_conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.admin_conversation_members (
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'member'::character varying,
  last_read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_conversation_members_pkey PRIMARY KEY (conversation_id, user_id),
  CONSTRAINT admin_conversation_members_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.admin_conversations(id),
  CONSTRAINT admin_conversation_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.admin_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_user_id uuid,
  body text NOT NULL,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  mentions ARRAY NOT NULL DEFAULT '{}'::uuid[],
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_messages_pkey PRIMARY KEY (id),
  CONSTRAINT admin_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.admin_conversations(id),
  CONSTRAINT admin_messages_sender_user_id_fkey FOREIGN KEY (sender_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.deleted_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_user_id uuid NOT NULL,
  role character varying,
  previous_status character varying,
  masked_email text,
  masked_phone text,
  email_hash text,
  phone_hash text,
  account_created_at timestamp without time zone,
  deleted_at timestamp without time zone NOT NULL DEFAULT now(),
  deletion_reason text NOT NULL DEFAULT 'user_requested'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT deleted_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sos_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_role text,
  user_name text,
  user_email text,
  user_phone text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'acknowledged'::text, 'resolved'::text, 'false_alarm'::text])),
  latitude double precision,
  longitude double precision,
  accuracy double precision,
  altitude double precision,
  heading double precision,
  speed double precision,
  full_address text,
  street text,
  place_name text,
  city text,
  region text,
  country text,
  postal_code text,
  active_ride_id uuid,
  active_ride_status text,
  active_ride_note text,
  driver_user_id uuid,
  driver_name text,
  driver_phone text,
  device_name text,
  device_brand text,
  device_model text,
  os_name text,
  os_version text,
  app_version text,
  raw_location jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_device jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sos_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT sos_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT sos_alerts_active_ride_id_fkey FOREIGN KEY (active_ride_id) REFERENCES public.rides(id),
  CONSTRAINT sos_alerts_driver_user_id_fkey FOREIGN KEY (driver_user_id) REFERENCES public.users(id),
  CONSTRAINT sos_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES public.users(id),
  CONSTRAINT sos_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.support_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  source_channel character varying NOT NULL DEFAULT 'in_app'::character varying CHECK (source_channel::text = ANY (ARRAY['in_app'::character varying, 'email'::character varying]::text[])),
  source_email text,
  source_name text,
  external_thread_id character varying,
  subject text,
  status character varying NOT NULL DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_message_at timestamp without time zone DEFAULT now(),
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT support_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT support_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.pricing_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT 'RAIL v1'::text,
  base_fare numeric NOT NULL DEFAULT 800 CHECK (base_fare >= 0::numeric),
  minimum_fare numeric NOT NULL DEFAULT 1500 CHECK (minimum_fare >= 0::numeric),
  per_minute numeric NOT NULL DEFAULT 15 CHECK (per_minute >= 0::numeric),
  platform_fee_rate numeric NOT NULL DEFAULT 0.15 CHECK (platform_fee_rate >= 0::numeric AND platform_fee_rate <= 1::numeric),
  eta_low_traffic_min_per_km numeric NOT NULL DEFAULT 4 CHECK (eta_low_traffic_min_per_km > 0::numeric),
  eta_normal_traffic_min_per_km numeric NOT NULL DEFAULT 6 CHECK (eta_normal_traffic_min_per_km > 0::numeric),
  eta_heavy_traffic_min_per_km numeric NOT NULL DEFAULT 8 CHECK (eta_heavy_traffic_min_per_km > 0::numeric),
  learning_weight numeric NOT NULL DEFAULT 0.1 CHECK (learning_weight >= 0::numeric AND learning_weight <= 1::numeric),
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pricing_settings_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT pricing_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.distance_bands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pricing_setting_id uuid NOT NULL,
  max_km numeric CHECK (max_km IS NULL OR max_km > 0::numeric),
  rate numeric NOT NULL CHECK (rate >= 0::numeric),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT distance_bands_pkey PRIMARY KEY (id),
  CONSTRAINT distance_bands_pricing_setting_id_fkey FOREIGN KEY (pricing_setting_id) REFERENCES public.pricing_settings(id)
);
CREATE TABLE public.route_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_key text NOT NULL UNIQUE,
  pickup_label text,
  destination_label text,
  ride_count integer NOT NULL DEFAULT 0 CHECK (ride_count >= 0),
  avg_minutes_per_km numeric NOT NULL DEFAULT 6 CHECK (avg_minutes_per_km > 0::numeric),
  morning_avg numeric,
  afternoon_avg numeric,
  evening_avg numeric,
  last_estimated_minutes numeric,
  last_actual_minutes numeric,
  last_distance_km numeric,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT route_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ride_pricing_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pricing_setting_id uuid,
  admin_user_id uuid,
  action text NOT NULL CHECK (action = ANY (ARRAY['created'::text, 'updated'::text, 'activated'::text])),
  previous_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  next_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ride_pricing_audit_pkey PRIMARY KEY (id),
  CONSTRAINT ride_pricing_audit_pricing_setting_id_fkey FOREIGN KEY (pricing_setting_id) REFERENCES public.pricing_settings(id),
  CONSTRAINT ride_pricing_audit_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.status_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  content text NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['service_update'::character varying, 'traffic_alert'::character varying, 'milestone'::character varying, 'notice'::character varying]::text[])),
  severity character varying NOT NULL DEFAULT 'info'::character varying CHECK (severity::text = ANY (ARRAY['info'::character varying, 'warning'::character varying, 'critical'::character varying, 'success'::character varying]::text[])),
  affected_zones ARRAY DEFAULT ARRAY[]::text[],
  created_by uuid,
  is_pinned boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT status_updates_pkey PRIMARY KEY (id),
  CONSTRAINT status_updates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.support_ai_memory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  memory_type text NOT NULL DEFAULT 'knowledge'::text CHECK (memory_type = ANY (ARRAY['knowledge'::text, 'correction'::text, 'policy'::text, 'route'::text, 'faq'::text, 'escalation'::text])),
  title text NOT NULL,
  content text NOT NULL,
  category text,
  audience text NOT NULL DEFAULT 'all'::text CHECK (audience = ANY (ARRAY['all'::text, 'rider'::text, 'driver'::text, 'support'::text, 'admin'::text])),
  route text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  source text NOT NULL DEFAULT 'manual'::text,
  source_entity_type text,
  source_entity_id uuid,
  confidence numeric NOT NULL DEFAULT 0.800 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  usefulness_score integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  expires_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT support_ai_memory_pkey PRIMARY KEY (id),
  CONSTRAINT support_ai_memory_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT support_ai_memory_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.support_ai_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  message_id uuid,
  user_id uuid,
  role text NOT NULL CHECK (role = ANY (ARRAY['rider'::text, 'driver'::text, 'support'::text, 'admin'::text, 'system'::text])),
  feedback_type text NOT NULL CHECK (feedback_type = ANY (ARRAY['corrected_answer'::text, 'wrong_role'::text, 'wrong_route'::text, 'too_many_questions'::text, 'helpful'::text, 'unhelpful'::text, 'escalate'::text])),
  original_reply text,
  corrected_reply text,
  correction_note text,
  route text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT support_ai_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT support_ai_feedback_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id),
  CONSTRAINT support_ai_feedback_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.ticket_messages(id),
  CONSTRAINT support_ai_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.mobile_push_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  body text NOT NULL,
  target_audience text NOT NULL DEFAULT 'all'::text,
  recipient_count integer NOT NULL DEFAULT 0,
  delivered_count integer NOT NULL DEFAULT 0,
  opened_count integer NOT NULL DEFAULT 0,
  image_url text,
  action_url text,
  cta_label text,
  category_id text NOT NULL DEFAULT 'mobile_campaign'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'cancelled'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  sent_at timestamp with time zone,
  last_sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mobile_push_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT mobile_push_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.mobile_push_campaign_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'read'::text, 'opened'::text])),
  error_message text,
  sent_at timestamp with time zone,
  opened_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mobile_push_campaign_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT mobile_push_campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.mobile_push_campaigns(id),
  CONSTRAINT mobile_push_campaign_recipients_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);